spring:
  application:
    name: file-receiver

mqtt:
  broker: tcp://localhost:1883
  client-id: file-receiver
  topic:
    file:
      meta-data: file-transfer/meta-data
      chunk: file-transfer/chunk
      transfer-completed: file-transfer/completed

server:
  port: 8081

app:
  folder-name: received_files