spring:
  application:
    name: file-sender
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

mqtt:
  broker: tcp://localhost:1883
  client-id: file-sender
  topic:
    file:
      meta-data: file-transfer/meta-data
      chunk: file-transfer/chunk
      transfer-completed: file-transfer/completed
      resend-file: file-transfer/resend-file

server:
  port: 8082

file:
  chunk-size: 1MB
  max-resend-times: 1

app:
  folder-name: file-sender/sent_files